version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "admin"]

  mongodb:
    image: mongo:7.0
    container_name: mongo_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  postgres:
    image: postgres:16
    container_name: postgres_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stockanalytics

volumes:
  redis_data:
  mongo_data:
  postgres_data: